checks:
    javascript: true
filter:
    excluded_paths:
        - "tests/"
        - "node_modules/"
build:
    environment:
        node: '9'
    tests:
        before:
            - command: npm run test:unit
        override:
            - php-scrutinizer-run